In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv("fitness_level_dataset.csv")
df.head()

,Workout_Hours_Per_Week,Calories_Burned_Avg,Sleep_Hours,BMI,Resting_Heart_Rate,Fitness_Level
0,4.5,292.0,6.3,26.5,82.0,Novice
1,2.0,178.0,6.1,32.0,90.0,Beginner
2,2.4,224.0,5.3,25.7,84.0,Beginner
3,5.6,434.0,6.3,25.2,67.0,Intermediate
4,2.6,208.0,5.7,28.1,72.0,Beginner

In [3]:
enco=LabelEncoder()
df["Fitness_Level"]=enco.fit_transform(df["Fitness_Level"])

In [4]:
df.head()

,Workout_Hours_Per_Week,Calories_Burned_Avg,Sleep_Hours,BMI,Resting_Heart_Rate,Fitness_Level
0,4.5,292.0,6.3,26.5,82.0,4
1,2.0,178.0,6.1,32.0,90.0,1
2,2.4,224.0,5.3,25.7,84.0,1
3,5.6,434.0,6.3,25.2,67.0,3
4,2.6,208.0,5.7,28.1,72.0,1

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=2)

In [17]:
scaler=StandardScaler()
X_train_scld=scaler.fit_transform(X_train)
X_test_scld=scaler.transform(X_test)

In [22]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scld,y_train)
y_pred=knn.predict(X_test_scld)

In [23]:
print(accuracy_score(y_test,y_pred))

1.0

# Noise free dataset